services:
  kinesisconsumer:
    container_name: kinesis-consumer
    image: kinesis-consumer-image
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Tokyo
      - AWS_ACCESS_KEY_ID={your_access_key}
      - AWS_SECRET_ACCESS_KEY={your_secret_key}
      - AWS_REGION=ap-northeast-1
